'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { useParams, useSearchParams } from 'next/navigation';
import dynamic from 'next/dynamic';
import type { editor } from 'monaco-editor';
import { API_URL, WS_URL, apiGet, apiPost, getAccessToken } from '@/lib/api';
import { Badge, Button, Select, Spinner } from '@/components/ui';
import { PreviewFrame } from '@/components/editor/PreviewFrame';
import { ChatPanel } from '@/components/editor/ChatPanel';
import { VersionTimeline } from '@/components/editor/VersionTimeline';
import { VisualEditor } from '@/components/editor/visual/VisualEditor';

const MonacoEditor = dynamic(() => import('@monaco-editor/react'), {
  ssr: false,
  loading: () => (
    <div className="flex h-full items-center justify-center">
      <Spinner />
    </div>
  ),
});

interface Bundle {
  files: Record<string, string>;
  entryFile: string;
  assets: Array<{ path: string; url: string; prompt: string; compressed: boolean }>;
  seo: unknown;
}

interface Project {
  id: string;
  name: string;
  type: string;
  brief: unknown;
}

interface GenJob {
  id: string;
  status: string;
  error?: string | null;
  result?: { versionId?: string; report?: { performanceScore: number; accessibilityScore: number } } | null;
}

const GEN_STATUS_LABELS: Record<string, string> = {
  QUEUED: 'Queued…',
  PLANNING: 'Planning layout & palette…',
  GENERATING: 'Writing the code…',
  VALIDATING: 'Validating HTML & contrast…',
  REVIEWING: 'AI reviewer auditing a11y/perf…',
  SEO_PASS: 'Optimizing SEO & sitemap…',
};

export default function ProjectEditorPage() {
  const { projectId } = useParams<{ projectId: string }>();
  const search = useSearchParams();

  const [project, setProject] = useState<Project | null>(null);
  const [files, setFiles] = useState<Record<string, string>>({});
  const [entryFile, setEntryFile] = useState('index.html');
  const [assets, setAssets] = useState<Bundle['assets']>([]);
  const [activeFile, setActiveFile] = useState<string | null>(null);
  const [editMode, setEditMode] = useState<'design' | 'code'>('design');
  const [designKey, setDesignKey] = useState(0);
  const [rightTab, setRightTab] = useState<'preview' | 'chat' | 'versions'>('preview');
  const [genStatus, setGenStatus] = useState<string | null>(null);
  const [deployProvider, setDeployProvider] = useState('VERCEL');
  const [deployInfo, setDeployInfo] = useState<string | null>(null);
  const [dirty, setDirty] = useState(false);
  const [toast, setToast] = useState<string | null>(null);

  const editorRef = useRef<editor.IStandaloneCodeEditor | null>(null);
  const collabCleanup = useRef<(() => void) | null>(null);
  const autoGenerated = useRef(false);

  const showToast = useCallback((msg: string) => {
    setToast(msg);
    setTimeout(() => setToast(null), 4000);
  }, []);

  const loadProject = useCallback(async () => {
    const res = await apiGet<{ project: Project; bundle: Bundle | null }>(`/projects/${projectId}`);
    setProject(res.project);
    if (res.bundle) {
      setFiles(res.bundle.files);
      setEntryFile(res.bundle.entryFile);
      setAssets(res.bundle.assets ?? []);
      setActiveFile((cur) => cur ?? res.bundle!.entryFile);
      // Remount the visual editor so it (re)loads the freshly fetched design.
      setDesignKey((k) => k + 1);
    }
    setDirty(false);
  }, [projectId]);

  useEffect(() => {
    void loadProject();
  }, [loadProject]);

  // ---------- Generation with status polling ----------
  const generate = useCallback(async () => {
    setGenStatus('QUEUED');
    try {
      const res = await apiPost<{ jobId: string }>(`/projects/${projectId}/generate`, {});
      const poll = async (): Promise<void> => {
        const { job } = await apiGet<{ job: GenJob }>(`/projects/${projectId}/jobs/${res.jobId}`);
        if (job.status === 'COMPLETED') {
          setGenStatus(null);
          await loadProject();
          const r = job.result?.report;
          showToast(
            r ? `Generated! Perf ${r.performanceScore} · A11y ${r.accessibilityScore}` : 'Generated!',
          );
          return;
        }
        if (job.status === 'FAILED') {
          setGenStatus(null);
          showToast(`Generation failed: ${job.error ?? 'unknown error'}`);
          return;
        }
        setGenStatus(job.status);
        setTimeout(() => void poll(), 2500);
      };
      setTimeout(() => void poll(), 2500);
    } catch (err) {
      setGenStatus(null);
      showToast(err instanceof Error ? err.message : 'Generation failed');
    }
  }, [projectId, loadProject, showToast]);

  useEffect(() => {
    if (search.get('autogenerate') === '1' && project && !autoGenerated.current) {
      autoGenerated.current = true;
      void generate();
    }
  }, [search, project, generate]);

  // ---------- Real-time collaboration (Yjs + y-monaco) ----------
  const bindCollab = useCallback(
    async (codeEditor: editor.IStandaloneCodeEditor, filePath: string) => {
      collabCleanup.current?.();
      try {
        const [Y, { WebsocketProvider }, { MonacoBinding }] = await Promise.all([
          import('yjs'),
          import('y-websocket'),
          import('y-monaco'),
        ]);
        const doc = new Y.Doc();
        const provider = new WebsocketProvider(`${WS_URL}/collab`, projectId, doc, {
          params: { token: getAccessToken() ?? '' },
        });
        const yText = doc.getText(filePath);
        provider.on('sync', (synced: boolean) => {
          if (synced && yText.length === 0) {
            yText.insert(0, files[filePath] ?? '');
          }
        });
        const model = codeEditor.getModel();
        if (!model) return;
        const binding = new MonacoBinding(yText, model, new Set([codeEditor]), provider.awareness);
        collabCleanup.current = () => {
          binding.destroy();
          provider.destroy();
          doc.destroy();
        };
      } catch {
        // Collaboration is best-effort: solo editing keeps working offline.
      }
    },
    [projectId, files],
  );

  useEffect(() => () => collabCleanup.current?.(), []);

  // ---------- Actions ----------
  async function saveVersion() {
    await apiPost(`/projects/${projectId}/versions`, { files, label: 'Manual save' });
    setDirty(false);
    showToast('Version saved');
  }

  // Lift live visual edits into shared state so Export/Deploy/Code stay in sync.
  const onDesignChange = useCallback((next: Record<string, string>) => {
    setFiles(next);
    setDirty(true);
  }, []);

  async function saveDesign(next: Record<string, string>) {
    await apiPost(`/projects/${projectId}/versions`, { files: next, label: 'Visual edit' });
    setFiles(next);
    setDirty(false);
    showToast('Design saved');
  }

  function switchMode(mode: 'design' | 'code') {
    // Re-sync the visual editor with any code-mode edits when returning to Design.
    if (mode === 'design') setDesignKey((k) => k + 1);
    setEditMode(mode);
  }

  async function aiInstruction(instruction: string) {
    try {
      const res = await apiPost<{ bundle: Bundle; changedFiles: string[] }>(
        `/projects/${projectId}/ai-edit`,
        { instruction },
      );
      setFiles(res.bundle.files);
      setAssets(res.bundle.assets ?? []);
      showToast(`AI updated: ${res.changedFiles.join(', ')}`);
    } catch (err) {
      showToast(err instanceof Error ? err.message : 'AI edit failed');
    }
  }

  async function exportZip() {
    const res = await fetch(`${API_URL}/api/v1/projects/${projectId}/export`, {
      headers: { Authorization: `Bearer ${getAccessToken()}` },
      credentials: 'include',
    });
    const blob = await res.blob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${project?.name ?? 'project'}.zip`;
    a.click();
    URL.revokeObjectURL(url);
  }

  async function deploy() {
    setDeployInfo('Deploying…');
    try {
      const res = await apiPost<{ deployment: { id: string; status: string; url?: string } }>(
        `/projects/${projectId}/deploy`,
        { provider: deployProvider },
      );
      const dep = res.deployment;
      if (dep.status === 'ERROR') {
        setDeployInfo('Deploy failed — check provider token in settings');
        return;
      }
      const poll = async (): Promise<void> => {
        const { deployment } = await apiGet<{ deployment: { status: string; url?: string } }>(
          `/projects/${projectId}/deployments/${dep.id}`,
        );
        if (deployment.status === 'READY') {
          setDeployInfo(`Live: ${deployment.url}`);
        } else if (deployment.status === 'ERROR') {
          setDeployInfo('Deploy failed');
        } else {
          setDeployInfo(`Status: ${deployment.status}…`);
          setTimeout(() => void poll(), 4000);
        }
      };
      setDeployInfo(dep.url ? `Building → ${dep.url}` : 'Building…');
      setTimeout(() => void poll(), 4000);
    } catch (err) {
      setDeployInfo(err instanceof Error ? err.message : 'Deploy failed');
    }
  }

  if (!project) {
    return (
      <div className="flex h-screen items-center justify-center">
        <Spinner className="h-6 w-6" />
      </div>
    );
  }

  const fileNames = Object.keys(files);

  return (
    <div className="flex h-screen flex-col">
      {/* Toolbar */}
      <div className="flex h-14 items-center gap-3 border-b border-slate-200 bg-white px-4">
        <h1 className="mr-2 truncate font-semibold">{project.name}</h1>
        <div className="flex overflow-hidden rounded-lg border border-slate-200">
          {(['design', 'code'] as const).map((m) => (
            <button
              key={m}
              onClick={() => switchMode(m)}
              className={`px-3 py-1.5 text-xs font-semibold capitalize ${
                editMode === m ? 'bg-brand-600 text-white' : 'bg-white text-slate-600 hover:bg-slate-50'
              }`}
            >
              {m === 'design' ? '🎨 Design' : '⟨⟩ Code'}
            </button>
          ))}
        </div>
        {dirty && <Badge variant="warning">Unsaved</Badge>}
        <Button size="sm" onClick={() => void generate()} disabled={genStatus !== null}>
          {genStatus ? (
            <>
              <Spinner className="border-white/40 border-t-white" /> {GEN_STATUS_LABELS[genStatus] ?? genStatus}
            </>
          ) : (
            '⚡ Generate'
          )}
        </Button>
        <Button size="sm" variant="outline" onClick={() => void saveVersion()} disabled={!fileNames.length}>
          Save version
        </Button>
        <Button size="sm" variant="outline" onClick={() => void exportZip()} disabled={!fileNames.length}>
          Export ZIP
        </Button>
        <div className="ml-auto flex items-center gap-2">
          <Select
            className="h-9 w-44"
            value={deployProvider}
            onChange={(e) => setDeployProvider(e.target.value)}
            aria-label="Deploy provider"
          >
            <option value="VERCEL">Vercel</option>
            <option value="NETLIFY">Netlify</option>
            <option value="GITHUB_PAGES">GitHub Pages</option>
            <option value="CLOUDFLARE_PAGES">Cloudflare Pages</option>
          </Select>
          <Button size="sm" variant="secondary" onClick={() => void deploy()} disabled={!fileNames.length}>
            Deploy
          </Button>
        </div>
      </div>

      {deployInfo && (
        <div className="border-b border-brand-100 bg-brand-50 px-4 py-2 text-sm text-brand-900">
          {deployInfo.startsWith('Live: ') ? (
            <a href={deployInfo.slice(6)} target="_blank" rel="noopener noreferrer" className="font-medium underline">
              {deployInfo}
            </a>
          ) : (
            deployInfo
          )}
        </div>
      )}

      {/* Workspace */}
      {editMode === 'design' ? (
        <VisualEditor
          key={designKey}
          files={files}
          entryFile={entryFile}
          assets={assets}
          onChange={onDesignChange}
          onSave={saveDesign}
        />
      ) : (
      <div className="flex min-h-0 flex-1">
        {/* Editor pane */}
        <div className="flex min-w-0 flex-1 flex-col border-r border-slate-200">
          <div className="flex items-center gap-1 overflow-x-auto border-b border-slate-200 bg-slate-100 px-2 py-1">
            {fileNames.map((name) => (
              <button
                key={name}
                onClick={() => setActiveFile(name)}
                className={`whitespace-nowrap rounded px-3 py-1 text-xs font-medium ${
                  activeFile === name ? 'bg-white shadow-sm' : 'text-slate-500 hover:bg-white/60'
                }`}
              >
                {name}
              </button>
            ))}
            {fileNames.length === 0 && (
              <span className="px-3 py-1 text-xs text-slate-400">No files yet — hit Generate</span>
            )}
          </div>
          <div className="min-h-0 flex-1">
            {activeFile && (
              <MonacoEditor
                key={activeFile}
                language={languageOf(activeFile)}
                value={files[activeFile]}
                onChange={(value) => {
                  setFiles((prev) => ({ ...prev, [activeFile]: value ?? '' }));
                  setDirty(true);
                }}
                onMount={(codeEditor) => {
                  editorRef.current = codeEditor;
                  void bindCollab(codeEditor, activeFile);
                }}
                options={{ minimap: { enabled: false }, fontSize: 13, wordWrap: 'on' }}
              />
            )}
          </div>
        </div>

        {/* Right pane */}
        <div className="flex w-[480px] flex-col">
          <div className="flex border-b border-slate-200 bg-white">
            {(['preview', 'chat', 'versions'] as const).map((tab) => (
              <button
                key={tab}
                onClick={() => setRightTab(tab)}
                className={`flex-1 py-2 text-sm font-medium capitalize ${
                  rightTab === tab ? 'border-b-2 border-brand-600 text-brand-700' : 'text-slate-500'
                }`}
              >
                {tab}
              </button>
            ))}
          </div>
          <div className="min-h-0 flex-1 overflow-hidden bg-slate-50">
            {rightTab === 'preview' && <PreviewFrame files={files} entryFile={entryFile} assets={assets} />}
            {rightTab === 'chat' && <ChatPanel projectId={projectId} onAiInstruction={aiInstruction} />}
            {rightTab === 'versions' && (
              <div className="h-full overflow-y-auto">
                <VersionTimeline projectId={projectId} onRestored={() => void loadProject()} />
              </div>
            )}
          </div>
        </div>
      </div>
      )}

      {toast && (
        <div role="status" className="fixed bottom-4 right-4 rounded-lg bg-slate-900 px-4 py-2 text-sm text-white shadow-lg">
          {toast}
        </div>
      )}
    </div>
  );
}

function languageOf(path: string): string {
  if (path.endsWith('.html')) return 'html';
  if (path.endsWith('.css')) return 'css';
  if (path.endsWith('.ts') || path.endsWith('.tsx')) return 'typescript';
  if (path.endsWith('.js') || path.endsWith('.jsx')) return 'javascript';
  if (path.endsWith('.json')) return 'json';
  if (path.endsWith('.xml')) return 'xml';
  return 'plaintext';
}
